name: 'Test CLI commands Action'

description: 'Github Action to test or check outputs of CLI commands 🕵️⚙️🖥'

inputs:

    command_line:
        description: 'The command line you want to run'
        required: true
    assert_file_path:
        description: 'repo/path/file.txt'
        required: true
    expected_result:
        description: 'PASSED or FAILED'
        required: false
        default: 'PASSED'
    specific_line:
        description: 'file line to compare'
        required: false

outputs:
  diff-output:
    description: "Diff output"
    value: ${{ steps.diff.outputs.result }}

runs:
  using: "composite"
  steps:

    - name: install strip-ansi-cli
      run: |
        echo 🚧 Installing strip-ansi-cli
        npm install --global strip-ansi-cli
      shell: bash

    - name: Create command output file
      run: |
        ${{ inputs.command_line }} &> output.txt || true
        echo 🚀 Command OUTPUT exported to output.txt file
      shell: bash

    - name: Diff commands
      id: diff
      run: |
        if [ -z ${{ inputs.specific_line }} ]; then
          echo 🕵️ Comparing files
          if diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) >/dev/null; then
            result=$(echo "PASSED")
          else
            result=$(echo "FAILED")
          fi
        else
          echo 🕵️ Comparing files specific line
          if diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi | tail -n ${{ inputs.specific_line }} ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi | tail -n ${{ inputs.specific_line }}) >/dev/null; then
            result=$(echo "PASSED")
          else
            result=$(echo "FAILED")
          fi
        fi
        echo ☞ DIFF command result is $result
        echo "::set-output name=result::$(echo $result)"
      shell: bash

    - run: |
        echo ☞ DIFF OUTPUT value is ${{ steps.diff.outputs.result }}
        echo ☞ DIFF EXPECTED value is ${{ inputs.expected_result }}
        if [ ${{ steps.diff.outputs.result }} != ${{ inputs.expected_result }} ]; then
          echo "❌ DIFF OUTPUT value NOT EQUAL to DIFF EXPECTED value!"
          if [ -z ${{ inputs.specific_line }} ]; then
          diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) | cat -t
          else
            diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi | tail -n ${{ inputs.specific_line }} ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi | tail -n ${{ inputs.specific_line }}) | cat -t
          fi
          exit 1
        else
          echo "✅ DIFF OUTPUT value EQUAL to DIFF EXPECTED value!"
        fi
      shell: bash

branding:
    icon: 'check'
    color: 'green'