name: 'Test CLI commands Action'

description: 'Github Action to test or check outputs of CLI commands 🕵️⚙️🖥'

inputs:

    command_line:
        description: 'The command line you want to run'
        required: true
    assert_file_path:
        description: 'repo/path/file.txt'
        required: true
    expected_result:
        description: 'PASSED or FAILED'
        required: false
        default: 'PASSED'
    specific_line:
        description: 'file line to compare'
        required: false

outputs:
  diff-output:
    description: "Diff output"
    value: ${{ steps.diff.outputs.result }}

runs:
  using: "composite"
  steps:

    - name: Create command output file
      run: ${{ inputs.command_line }} &> output.txt || true
      shell: bash
    
    - run: echo 👍 Command OUTPUT exported to output.txt file
      shell: bash

    - name: Diff commands
      id: diff
      run: |
        if [ -z ${{ inputs.specific_line }} ]; then
          echo Comparing files
          sed 's/^M// output.txt > file1.txt
          sed 's/^M// ${{ inputs.assert_file_path }} > file2.txt
          if diff file1.txt file2.txt >/dev/null; then
            result=$(echo "PASSED")
          else
            result=$(echo "FAILED")
          fi
        else
          echo Comparing files specific line
          if diff <(head -n ${{ inputs.specific_line }} file1.txt) <(head -n ${{ inputs.specific_line }} file2.txt ) >/dev/null; then
            result=$(echo "PASSED")
          else
            result=$(echo "FAILED")
          fi
        fi
        echo ↔️ DIFF command result is $result
        echo "::set-output name=result::$(echo $result)"
      shell: bash

    - run: |
        echo ➡️ DIFF OUTPUT value is ${{ steps.diff.outputs.result }}
        echo ➡️ DIFF EXPECTED value is ${{ inputs.expected_result }}
        if [ ${{ steps.diff.outputs.result }} != ${{ inputs.expected_result }} ]; then
          echo "❌ DIFF OUTPUT value NOT EQUAL to DIFF EXPECTED value!"
          if [ -z ${{ inputs.specific_line }} ]; then
            diff file1.txt file2.txt | cat -t
          else
            diff <(head -n ${{ inputs.specific_line }} file1.txt) <(head -n ${{ inputs.specific_line }} file2.txt ) | cat -t
          fi
          exit 1
        else
          echo "✅ DIFF OUTPUT value EQUAL to DIFF EXPECTED value!"
        fi
      shell: bash

branding:
    icon: 'check'
    color: 'green'