name: 'Test CLI commands Action'

description: 'Github Action to test or check outputs of CLI commands 🕵️⚙️🖥'

inputs:

    command_line:
        description: 'The command line you want to run'
        required: true
    assert_file_path:
        description: 'repo/path/file.txt'
        required: false
    expected_result:
        description: 'PASSED or FAILED'
        required: false
        default: 'PASSED'
    specific_line:
        description: 'file line to compare'
        required: false
    contains: 
        description: 'String the file must contain'
        required: false

outputs:
  diff-output:
    description: "Comparision output"
    value: ${{ steps.comparision.outputs.result }}

runs:
  using: "composite"
  steps:

    - name: install strip-ansi-cli
      run: |
        echo 🚧 Installing strip-ansi-cli
        npm install --global strip-ansi-cli
      shell: bash

    - name: Create command output file
      run: |
        ${{ inputs.command_line }} &> output.txt || true
        echo 🚀 Command OUTPUT exported to output.txt file
      shell: bash

    - name: Comparision
      id: comparision
      run: |
        if [ ! -z ${{ inputs.contains }} ]; then
            echo 🕵️ Check if output file contains expression \"${{ inputs.contains }}\"
            if grep -q "${{ inputs.contains }}" output.txt; then
                result=$(echo "PASSED")
            else
                result=$(echo "FAILED")
            fi
        elif [ ! -z ${{ inputs.specific_line }} ]; then
            echo 🕵️ Comparing files specific line
            if diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi ) >/dev/null; then
                result=$(echo "PASSED")
            else
                result=$(echo "FAILED")
            fi
        else
            echo 🕵️ Comparing files
            if diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) >/dev/null; then
                result=$(echo "PASSED")
            else
                result=$(echo "FAILED")
            fi
        fi
        echo "::set-output name=result::$(echo $result)"
      shell: bash

    - run: |
        echo 🆚 GOT vs EXPECTED
        echo ▶️ GOT: ${{ steps.comparision.outputs.result }}
        echo ▶️ EXPECTED: ${{ inputs.expected_result }}
        if [ ${{ steps.comparision.outputs.result }} != ${{ inputs.expected_result }} ]; then
            echo "❌ GOT result NOT EQUAL to EXPECTED result!"
            if [ ! -z ${{ inputs.contains }} ]; then
                echo "Command output doesn't contain \"${{ inputs.contains }}\""
                cat output.txt
            elif [ ! -z ${{ inputs.specific_line }} ]; then
                diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi ) | cat -t
            else
                diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) | cat -t
            fi
            exit 1
        else
            echo ✅ GOT result EQUAL to EXPECTED result!
        fi
      shell: bash

branding:
    icon: 'check'
    color: 'green'