name: Test V2

on:
  push:
  workflow_dispatch:

jobs:
  PASSED-assert-file:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: GuillaumeFalourd/check-command-line-output@v2
        with:
          command_line: cat action.yml
          assert_file_path: action.yml
          expected_result: PASSED

  FAILED-assert-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: GuillaumeFalourd/check-command-line-output@v2
        with:
          command_line: ls -lha
          assert_file_path: assert.txt
          expected_result: FAILED

  PASSED-specific-line:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: GuillaumeFalourd/check-command-line-output@v2
        with:
          command_line: cat action.yml
          assert_file_path: action.yml
          expected_result: PASSED
          specific_line: 1